#!/bin/bash
#SBATCH -J tabela_kraken_run 					 # A single job name for the array
#SBATCH -n 32                # Number of cores
#SBATCH -N 1                 # Number of nodes for the cores
#SBATCH -t 0-00:30           # Runtime in D-HH:MM format
#SBATCH -p desai    # Partition to submit to
#SBATCH --mem=120G           # Memory pool for all CPUs
#SBATCH -o /n/desai_lab/users/aromanosilva/kraken_out/tabela2_run.out     # File to which standard out will be written
#SBATCH -e /n/desai_lab/users/aromanosilva/kraken_out/tabela2_run.err     # File to which standard err will be written
#SBATCH --mail-type=ALL      # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=a163861@dac.unicamp.br  #Email to which notifications will be sent

echo 70 0.5 tabela_genero_total.csv tabela_especie_total.csv total_kraken.csv AKG1_report_total.txt AKG2_report_total.txt AKG3_report_total.txt AKG4_report_total.txt AKG5_report_total.txt AKG6_report_total.txt AKG7_report_total.txt AKG8_report_total.txt AKG9_report_total.txt AKG10_report_total.txt AKG11_report_total.txt AKG12_report_total.txt AKG13_report_total.txt AKG14_report_total.txt AKG15_report_total.txt AKG16_report_total.txt AKG17_report_total.txt AKG18_report_total.txt AKG27_report_total.txt AKG28_report_total.txt AKG29_report_total.txt AKG30_report_total.txt AKG31_report_total.txt AKG32_report_total.txt AKG33_report_total.txt AKG34_report_total.txt AKG35_report_total.txt AKG36_report_total.txt AKG37_report_total.txt AKG38_report_total.txt AKG39_report_total.txt AKG40_report_total.txt AKG41_report_total.txt AKG42_report_total.txt AKG43_report_total.txt AKG44_report_total.txt AKG45_report_total.txt AKG46_report_total.txt AKG47_report_total.txt AKG48_report_total.txt AKG124_report_total.txt AKG125_report_total.txt AKG126_report_total.txt AKG127_report_total.txt AKG128_report_total.txt AKG129_report_total.txt AKG130_report_total.txt AKG131_report_total.txt AKG132_report_total.txt AKG133_report_total.txt AKG134_report_total.txt AKG135_report_total.txt AKG136_report_total.txt AKG137_report_total.txt AKG138_report_total.txt AKG139_report_total.txt AKG140_report_total.txt AKG141_report_total.txt AKG142_report_total.txt AKG143_report_total.txt AKG144_report_total.txt AKG145_report_total.txt AKG146_report_total.txt AKG147_report_total.txt AKG148_report_total.txt AKG149_report_total.txt AKG150_report_total.txt AKG151_report_total.txt AKG152_report_total.txt AKG153_report_total.txt | ./tabela_kraken.exe

echo 19 2 generos_UIR_2018_total.csv especies_UIR_2018_total.csv total_UIR_2018.csv AKG1_report_total.txt AKG2_report_total.txt AKG3_report_total.txt AKG4_report_total.txt AKG5_report_total.txt AKG6_report_total.txt AKG7_report_total.txt AKG8_report_total.txt AKG9_report_total.txt AKG27_report_total.txt AKG28_report_total.txt AKG29_report_total.txt AKG30_report_total.txt AKG31_report_total.txt AKG32_report_total.txt AKG33_report_total.txt AKG34_report_total.txt AKG35_report_total.txt AKG36_report_total.txt | ./tabela_kraken.exe

echo 15 2 generos_UIR_2019_total.csv especies_UIR_2019_total.csv total_UIR_2019.csv AKG124_report_total.txt AKG125_report_total.txt AKG126_report_total.txt AKG127_report_total.txt AKG128_report_total.txt AKG129_report_total.txt AKG130_report_total.txt AKG131_report_total.txt AKG132_report_total.txt AKG133_report_total.txt AKG134_report_total.txt AKG135_report_total.txt AKG136_report_total.txt AKG137_report_total.txt AKG138_report_total.txt | ./tabela_kraken.exe

echo 21 2 generos_UCP_2018_total.csv especies_UCP_2018_total.csv total_UCP_2018.csv AKG10_report_total.txt AKG11_report_total.txt AKG12_report_total.txt AKG13_report_total.txt AKG14_report_total.txt AKG15_report_total.txt AKG16_report_total.txt AKG17_report_total.txt AKG18_report_total.txt AKG37_report_total.txt AKG38_report_total.txt AKG39_report_total.txt AKG40_report_total.txt AKG41_report_total.txt AKG42_report_total.txt AKG43_report_total.txt AKG44_report_total.txt AKG45_report_total.txt AKG46_report_total.txt AKG47_report_total.txt AKG48_report_total.txt | ./tabela_kraken.exe

echo 15 2 generos_UCP_2019_total.csv especies_UCP_2019_total.csv total_UCP_2019.csv AKG139_report_total.txt AKG140_report_total.txt AKG141_report_total.txt AKG142_report_total.txt AKG143_report_total.txt AKG144_report_total.txt AKG145_report_total.txt AKG146_report_total.txt AKG147_report_total.txt AKG148_report_total.txt AKG149_report_total.txt AKG150_report_total.txt AKG151_report_total.txt AKG152_report_total.txt AKG153_report_total.txt | ./tabela_kraken.exe
